/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AggComposite } from '../models/AggComposite';
import { AggHistogram } from '../models/AggHistogram';
import { AggTerms } from '../models/AggTerms';
import { HttpFile } from '../http/http';

export class Aggregation {
    'terms'?: AggTerms;
    'sort'?: Array<any>;
    'composite'?: AggComposite;
    'histogram'?: AggHistogram;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "terms",
            "baseName": "terms",
            "type": "AggTerms",
            "format": ""
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "composite",
            "baseName": "composite",
            "type": "AggComposite",
            "format": ""
        },
        {
            "name": "histogram",
            "baseName": "histogram",
            "type": "AggHistogram",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Aggregation.attributeTypeMap;
    }

    public constructor() {
    }
}
