/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Success response for bulk search requests
*/
export class BulkResponse {
    /**
    * List of results
    */
    'items'?: Array<any>;
    /**
    * Errors occurred during the bulk operation
    */
    'errors'?: boolean;
    /**
    * Error message describing an error if such occurred
    */
    'error'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BulkResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
