/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Payload for delete request. Documents can be deleted either one by one by specifying the document id or by providing a query object. For more information see  [Delete API](https://manual.manticoresearch.com/Deleting_documents) 
*/
export class DeleteDocumentRequest {
    /**
    * Table name
    */
    'table': string;
    /**
    * Cluster name
    */
    'cluster'?: string;
    /**
    * The ID of document for deletion
    */
    'id'?: number;
    /**
    * Defines the criteria to match documents for deletion
    */
    'query'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "table",
            "baseName": "table",
            "type": "string",
            "format": ""
        },
        {
            "name": "cluster",
            "baseName": "cluster",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeleteDocumentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
