/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Defines a type of filter for full-text search queries
*/
export class FulltextFilter {
    /**
    * Filter object defining a query string
    */
    'query_string'?: string;
    /**
    * Filter object defining a match keyword passed as a string or in a Match object
    */
    'match'?: any;
    /**
    * Filter object defining a match phrase
    */
    'match_phrase'?: any;
    /**
    * Filter object to select all documents
    */
    'match_all'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "query_string",
            "baseName": "query_string",
            "type": "string",
            "format": ""
        },
        {
            "name": "match",
            "baseName": "match",
            "type": "any",
            "format": ""
        },
        {
            "name": "match_phrase",
            "baseName": "match_phrase",
            "type": "any",
            "format": ""
        },
        {
            "name": "match_all",
            "baseName": "match_all",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FulltextFilter.attributeTypeMap;
    }

    public constructor() {
    }
}
