/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* List of fields available for highlighting
*/
/**
 * @type HighlightFields
 * Type
 * @export
 */
export type HighlightFields = Array<string> | any;

/**
* @type HighlightFieldsClass
    * List of fields available for highlighting
* @export
*/
export class HighlightFieldsClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

