/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Search hit representing a matched document
*/
export class HitsHits {
    /**
    * The ID of the matched document
    */
    '_id'?: number;
    /**
    * The score of the matched document
    */
    '_score'?: number;
    /**
    * The source data of the matched document
    */
    '_source'?: any;
    /**
    * The knn distance of the matched document returned for knn queries
    */
    '_knn_dist'?: number;
    /**
    * The highlighting-related data of the matched document
    */
    'highlight'?: any;
    /**
    * The table name of the matched document returned for percolate queries
    */
    'table'?: string;
    /**
    * The type of the matched document returned for percolate queries
    */
    '_type'?: string;
    /**
    * The percolate-related fields of the matched document returned for percolate queries
    */
    'fields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_id",
            "baseName": "_id",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "_score",
            "baseName": "_score",
            "type": "number",
            "format": ""
        },
        {
            "name": "_source",
            "baseName": "_source",
            "type": "any",
            "format": ""
        },
        {
            "name": "_knn_dist",
            "baseName": "_knn_dist",
            "type": "number",
            "format": ""
        },
        {
            "name": "highlight",
            "baseName": "highlight",
            "type": "any",
            "format": ""
        },
        {
            "name": "table",
            "baseName": "table",
            "type": "string",
            "format": ""
        },
        {
            "name": "_type",
            "baseName": "_type:",
            "type": "string",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HitsHits.attributeTypeMap;
    }

    public constructor() {
    }
}
