/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Object containing data for inserting a new document into the table 
*/
export class InsertDocumentRequest {
    /**
    * Name of the table to insert the document into
    */
    'table': string;
    /**
    * Name of the cluster to insert the document into
    */
    'cluster'?: string;
    /**
    * Document ID. If not provided, an ID will be auto-generated 
    */
    'id'?: number;
    /**
    * Object containing document data 
    */
    'doc': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "table",
            "baseName": "table",
            "type": "string",
            "format": ""
        },
        {
            "name": "cluster",
            "baseName": "cluster",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "doc",
            "baseName": "doc",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InsertDocumentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
