/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FulltextFilter } from '../models/FulltextFilter';
import { JoinOn } from '../models/JoinOn';
import { HttpFile } from '../http/http';

export class Join {
    /**
    * Type of the join operation
    */
    'type': JoinTypeEnum;
    /**
    * List of objects defining joined tables
    */
    'on': Array<JoinOn>;
    'query'?: FulltextFilter;
    /**
    * Basic table of the join operation
    */
    'table': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "JoinTypeEnum",
            "format": ""
        },
        {
            "name": "on",
            "baseName": "on",
            "type": "Array<JoinOn>",
            "format": ""
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "FulltextFilter",
            "format": ""
        },
        {
            "name": "table",
            "baseName": "table",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Join.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum JoinTypeEnum {
    inner = 'inner',
    left = 'left'
}

