/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FulltextFilter } from '../models/FulltextFilter';
import { HttpFile } from '../http/http';

/**
* Object representing the conditions used to perform the join operation
*/
export class JoinCond {
    /**
    * Field to join on
    */
    'field': string;
    /**
    * Joined table
    */
    'table': string;
    'query'?: FulltextFilter;
    'type'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "string",
            "format": ""
        },
        {
            "name": "table",
            "baseName": "table",
            "type": "string",
            "format": ""
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "FulltextFilter",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JoinCond.attributeTypeMap;
    }

    public constructor() {
    }
}
