/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Filter helper object defining a match keyword and match options
*/
export class Match {
    'query': string;
    'operator'?: MatchOperatorEnum;
    'boost'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "query",
            "baseName": "query",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "MatchOperatorEnum",
            "format": ""
        },
        {
            "name": "boost",
            "baseName": "boost",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Match.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum MatchOperatorEnum {
    or = 'or',
    and = 'and'
}

