/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Detailed error information returned in case of an error response
*/
export class ResponseErrorDetails {
    /**
    * Type or category of the error
    */
    'type': string;
    /**
    * Detailed explanation of why the error occurred
    */
    'reason'?: string | null;
    /**
    * The index related to the error, if applicable
    */
    'index'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResponseErrorDetails.attributeTypeMap;
    }

    public constructor() {
    }
}
