/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResponseErrorDetails } from '../models/ResponseErrorDetails';
import { HttpFile } from '../http/http';

/**
 * @type ResponseError
 * Type
 * @export
 */
export type ResponseError = ResponseErrorDetails | string;

/**
* @type ResponseErrorClass
* @export
*/
export class ResponseErrorClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

