/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HitsHits } from '../models/HitsHits';
import { HttpFile } from '../http/http';

/**
* Object containing the search hits, which represent the documents that matched the query.
*/
export class SearchResponseHits {
    /**
    * Maximum score among the matched documents
    */
    'max_score'?: number;
    /**
    * Total number of matched documents
    */
    'total'?: number;
    /**
    * Indicates whether the total number of hits is accurate or an estimate
    */
    'total_relation'?: string;
    /**
    * Array of hit objects, each representing a matched document
    */
    'hits'?: Array<HitsHits>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "max_score",
            "baseName": "max_score",
            "type": "number",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "total_relation",
            "baseName": "total_relation",
            "type": "string",
            "format": ""
        },
        {
            "name": "hits",
            "baseName": "hits",
            "type": "Array<HitsHits>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchResponseHits.attributeTypeMap;
    }

    public constructor() {
    }
}
