/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BoolFilter } from '../models/BoolFilter';
import { GeoDistance } from '../models/GeoDistance';
import { Highlight } from '../models/Highlight';
import { HttpFile } from '../http/http';

/**
* Defines a query structure for performing search operations
*/
export class SearchQuery {
    /**
    * Filter object defining a query string
    */
    'query_string'?: string;
    /**
    * Filter object defining a match keyword passed as a string or in a Match object
    */
    'match'?: any;
    /**
    * Filter object defining a match phrase
    */
    'match_phrase'?: any;
    /**
    * Filter object to select all documents
    */
    'match_all'?: any;
    'bool'?: BoolFilter;
    'equals'?: any | null;
    /**
    * Filter to match a given set of attribute values.
    */
    'in'?: any;
    /**
    * Filter to match a given range of attribute values passed in Range objects
    */
    'range'?: any;
    'geo_distance'?: GeoDistance;
    'highlight'?: Highlight;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "query_string",
            "baseName": "query_string",
            "type": "string",
            "format": ""
        },
        {
            "name": "match",
            "baseName": "match",
            "type": "any",
            "format": ""
        },
        {
            "name": "match_phrase",
            "baseName": "match_phrase",
            "type": "any",
            "format": ""
        },
        {
            "name": "match_all",
            "baseName": "match_all",
            "type": "any",
            "format": ""
        },
        {
            "name": "bool",
            "baseName": "bool",
            "type": "BoolFilter",
            "format": ""
        },
        {
            "name": "equals",
            "baseName": "equals",
            "type": "any",
            "format": ""
        },
        {
            "name": "in",
            "baseName": "in",
            "type": "any",
            "format": ""
        },
        {
            "name": "range",
            "baseName": "range",
            "type": "any",
            "format": ""
        },
        {
            "name": "geo_distance",
            "baseName": "geo_distance",
            "type": "GeoDistance",
            "format": ""
        },
        {
            "name": "highlight",
            "baseName": "highlight",
            "type": "Highlight",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchQuery.attributeTypeMap;
    }

    public constructor() {
    }
}
