/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchResponseHits } from '../models/SearchResponseHits';
import { HttpFile } from '../http/http';

/**
* Response object containing the results of a search request
*/
export class SearchResponse {
    /**
    * Time taken to execute the search
    */
    'took'?: number;
    /**
    * Indicates whether the search operation timed out
    */
    'timed_out'?: boolean;
    /**
    * Aggregated search results grouped by the specified criteria
    */
    'aggregations'?: any;
    'hits'?: SearchResponseHits;
    /**
    * Profile information about the search execution, if profiling is enabled
    */
    'profile'?: any;
    /**
    * Warnings encountered during the search operation
    */
    'warning'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "took",
            "baseName": "took",
            "type": "number",
            "format": ""
        },
        {
            "name": "timed_out",
            "baseName": "timed_out",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "aggregations",
            "baseName": "aggregations",
            "type": "any",
            "format": ""
        },
        {
            "name": "hits",
            "baseName": "hits",
            "type": "SearchResponseHits",
            "format": ""
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "any",
            "format": ""
        },
        {
            "name": "warning",
            "baseName": "warning",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
