/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Aggregation } from '../models/Aggregation';
import { Highlight } from '../models/Highlight';
import { Join } from '../models/Join';
import { KnnQuery } from '../models/KnnQuery';
import { SearchQuery } from '../models/SearchQuery';
import { HttpFile } from '../http/http';

/**
* Request object for search operation
*/
export class SearchRequest {
    /**
    * The table to perform the search on
    */
    'table': string;
    'query'?: SearchQuery;
    /**
    * Join clause to combine search data from multiple tables
    */
    'join'?: Array<Join>;
    'highlight'?: Highlight;
    /**
    * Maximum number of results to return
    */
    'limit'?: number;
    'knn'?: KnnQuery;
    /**
    * Defines aggregation settings for grouping results
    */
    'aggs'?: { [key: string]: Aggregation; } | null;
    /**
    * Expressions to calculate additional values for the result
    */
    'expressions'?: { [key: string]: string; } | null;
    /**
    * Maximum number of matches allowed in the result
    */
    'max_matches'?: number;
    /**
    * Starting point for pagination of the result
    */
    'offset'?: number;
    /**
    * Additional search options
    */
    'options'?: any;
    /**
    * Enable or disable profiling of the search request
    */
    'profile'?: boolean;
    'sort'?: any | null;
    '_source'?: any | null;
    /**
    * Enable or disable result weight calculation used for sorting
    */
    'track_scores'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "table",
            "baseName": "table",
            "type": "string",
            "format": ""
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "SearchQuery",
            "format": ""
        },
        {
            "name": "join",
            "baseName": "join",
            "type": "Array<Join>",
            "format": ""
        },
        {
            "name": "highlight",
            "baseName": "highlight",
            "type": "Highlight",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "knn",
            "baseName": "knn",
            "type": "KnnQuery",
            "format": ""
        },
        {
            "name": "aggs",
            "baseName": "aggs",
            "type": "{ [key: string]: Aggregation; }",
            "format": ""
        },
        {
            "name": "expressions",
            "baseName": "expressions",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "max_matches",
            "baseName": "max_matches",
            "type": "number",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "any",
            "format": ""
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "any",
            "format": ""
        },
        {
            "name": "_source",
            "baseName": "_source",
            "type": "any",
            "format": ""
        },
        {
            "name": "track_scores",
            "baseName": "track_scores",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
