/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SqlObjResponse } from '../models/SqlObjResponse';
import { HttpFile } from '../http/http';

/**
* List of responses from executed SQL queries
*/
/**
 * @type SqlResponse
 * Type
 * @export
 */
export type SqlResponse = Array<any> | SqlObjResponse;

/**
* @type SqlResponseClass
    * List of responses from executed SQL queries
* @export
*/
export class SqlResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

