/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Response object indicating the success of an operation, such as inserting or updating a document
*/
export class SuccessResponse {
    /**
    * Name of the document table
    */
    'table'?: string;
    /**
    * ID of the document affected by the request operation
    */
    'id'?: number;
    /**
    * Indicates whether the document was created as a result of the operation
    */
    'created'?: boolean;
    /**
    * Result of the operation, typically \'created\', \'updated\', or \'deleted\'
    */
    'result'?: string;
    /**
    * Indicates whether the document was found in the table
    */
    'found'?: boolean;
    /**
    * HTTP status code representing the result of the operation
    */
    'status'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "table",
            "baseName": "table",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "string",
            "format": ""
        },
        {
            "name": "found",
            "baseName": "found",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SuccessResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
