/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Success response returned after updating one or more documents
*/
export class UpdateResponse {
    /**
    * Name of the document table
    */
    'table'?: string;
    /**
    * Number of documents updated
    */
    'updated'?: number;
    /**
    * Document ID
    */
    '_id'?: number;
    /**
    * Result of the update operation, typically \'updated\'
    */
    'result'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "table",
            "baseName": "table",
            "type": "string",
            "format": ""
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "number",
            "format": ""
        },
        {
            "name": "_id",
            "baseName": "_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
