/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QueryFilter } from '../models/QueryFilter';
import { HttpFile } from '../http/http';

/**
* Payload for updating a document or multiple documents in a table
*/
export class UpdateDocumentRequest {
    /**
    * Name of the document table
    */
    'table': string;
    /**
    * Name of the document cluster
    */
    'cluster'?: string;
    /**
    * Object containing the document fields to update
    */
    'doc': any;
    /**
    * Document ID
    */
    'id'?: number;
    'query'?: QueryFilter | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "table",
            "baseName": "table",
            "type": "string",
            "format": ""
        },
        {
            "name": "cluster",
            "baseName": "cluster",
            "type": "string",
            "format": ""
        },
        {
            "name": "doc",
            "baseName": "doc",
            "type": "any",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "QueryFilter",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateDocumentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
